###############################################################
# 直接通过服务名访问服务
###############################################################

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #是否可以通过服务名直接访问到对应服务，默认false，即通过127.0.0.1:8888/{服务名}/{服务API地址}访问对应服务
