spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: gateway
        register-enabled: false # 当前网关服务可以不用注册到nacos，这里使用nacos是为了从nacos获取服务列表
  application:
    name: gateway-server-app
  profiles:
    active: path
server:
  port: 8888
