spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: gateway
        metadata:
          tag: 8013
  application:
    name: service-A-app
server:
  port: 8013
